# Generated by Django 6.0.4 on 2026-05-27 00:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='投票标题')),
                ('description', models.TextField(blank=True, verbose_name='投票描述')),
                ('poll_type', models.CharField(choices=[('single', '单题投票'), ('multiple', '多题调查')], default='single', max_length=20, verbose_name='投票类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('require_login', models.BooleanField(default=False, verbose_name='需要登录')),
                ('collect_location', models.BooleanField(default=False, verbose_name='收集地区信息')),
                ('collect_age', models.BooleanField(default=False, verbose_name='收集年龄段')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='二维码')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '投票',
                'verbose_name_plural': '投票',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500, verbose_name='问题内容')),
                ('question_type', models.CharField(choices=[('single_choice', '单选题'), ('multiple_choice', '多选题')], default='single_choice', max_length=20, verbose_name='问题类型')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.poll', verbose_name='所属投票')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200, verbose_name='选项内容')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.question', verbose_name='所属问题')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, verbose_name='会话ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='地区')),
                ('age_group', models.CharField(blank=True, choices=[('under_18', '18岁以下'), ('18_25', '18-25岁'), ('26_35', '26-35岁'), ('36_45', '36-45岁'), ('46_55', '46-55岁'), ('over_55', '55岁以上')], max_length=20, null=True, verbose_name='年龄段')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='投票时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='polls.question', verbose_name='问题')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='polls.option', verbose_name='选中选项')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '投票记录',
                'verbose_name_plural': '投票记录',
                'ordering': ['-voted_at'],
            },
        ),
        migrations.CreateModel(
            name='IPLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('vote_count', models.IntegerField(default=0, verbose_name='投票次数')),
                ('last_vote_at', models.DateTimeField(auto_now=True, verbose_name='最后投票时间')),
                ('window_start', models.DateTimeField(auto_now_add=True, verbose_name='时间窗口开始')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_limits', to='polls.poll', verbose_name='投票')),
            ],
            options={
                'verbose_name': 'IP限制',
                'verbose_name_plural': 'IP限制',
                'unique_together': {('ip_address', 'poll')},
            },
        ),
    ]
